<h2>Combats</h2>
<?php if (User::isLogged()) {

    // Fleet selection
    if ($select_fleet) {
        if (count($troops) > 0 && $army->total_units > 0) {
            ?>
            <form method="post" id="unit-selection">
                <?php echo clean_html($user->pseudo) . ' VS ' . clean_html($target->pseudo) ?>
                <input type="hidden" name="target_id" value="<?php echo $target->id ?>">
                <table class="col-8 center sm-full">
                    <?php
                    foreach ($army_owned->troops as $troop) {
                        if ($troop->quantity > 0) {
                            ?>
                            <tbody>
                            <tr>
                                <td><?php echo $troop->name ?></td>
                                <td class="unit-quantity"><label><input type="number" class="js-quantity input-number"
                                                                        name="unitID_<?php echo $troop->unit_id ?>"
                                                                        placeholder="0" min="0"
                                                                        max="<?php echo $troop->quantity ?>">/ <?php echo $troop->quantity ?>
                                    </label></td>
                            </tr>
                            <tr>
                                <td colspan="3">
                                    <div class="slider" data-max="<?php echo $troop->quantity ?>"></div>
                                </td>
                            </tr>
                            </tbody>
                        <?php
                        }
                    }
                    ?>
                    <tr>
                        <td></td>
                        <td>
                            <button type="submit" name="start_war">start_war</button>
                        </td>
                    </tr>
                </table>
            </form>
        <?php
        } else {
            ?>
            <p>Vous n'avez pas d'unités à envoyer</p>
        <?php
        }

        // Target Choice
    } else {
        ?>
        <ul class="players-list col-4 center">
            <?php
            if (!empty($targets)) {
                foreach ($targets as $target) {
                    if ($user->id != $target['id'])
                        echo '<li><a href="' . _ROOT_ . 'war/attack/' . $target['id'] . '">' . clean_html(($target['pseudo'])) . ' - ' . $target['score'] . '</a></li>';
                }
            } else {
                $errors[] = 'Aucun utilisateur de votre niveau à portée';
            } ?>
        </ul>

    <?php } ?>

    <script>
        $(function(){
            $('.slider').slider({
                animate : 'slow',
                min : 0,
                max : $(this).data('max'),
                step : 1,
                slide : function(evt, target){
                    var qty = Math.floor($(this).data('max') * target.value / 100);
                    $(this).closest('tbody').find('.js-quantity').val(qty);
                }
            });
            $('.js-quantity').blur(function(e){
                var slider = $(this).closest('tbody').find('.slider');
                var quantity = $(this).val() / slider.data('max') * 100;
                slider.slider({value : quantity})
            })
        });
    </script>
<?php
} else {
    echo '<p>Vous n\'avez rien à faire ici</p>';
}?>
