<table>
    <thead>
    <tr>
        <th class="col-6">
            Attaquant : <?= $attacker->pseudo ?>
            <small><?= $army_att->get_total_units() ?> unité(s)</small>
        </th>
        <th class="col-6">
            Défenseur :<?= $defender->pseudo ?>
            <small><?= $army_att->get_total_units() ?> unité(s)</small>
        </th>
    </tr>
    <tr>
        <td>
            <ul>
                <?php foreach ($army_att->get_troops() as $unit): ?>
                    <?php if ($unit['quantity'] > 0): ?>
                        <li><?= $unit['quantity'] ?> <?= $unit['name'] ?></li>
                    <?php endif ?>
                <?php endforeach ?>
            </ul>
        </td>
        <td>
            <ul>
                <?php if ($army_def->get_total_units() > 0): ?>
                    <?php foreach ($army_def->get_troops() as $unit): ?>
                        <li><?= $unit['quantity'] ?> <?= $unit['name'] ?></li>
                    <?php endforeach ?>
                <?php else: ?>
                    <li>Il n'y avait personne pour défendre cet empire</li>";
                <?php endif ?>
            </ul>
        </td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($turns as $count => $turn): ?>
        <tr>
            <th colspan="2" class="text-center">Tour <?= $count ?></th>
        </tr>
        <tr>
            <td><?= $turn['att'] ?></td>
            <td><?= $turn['def'] ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan='2'>
            <?php if ($army_def->get_total_units() <= 0): ?>
                Vainqueur : <?= $attacker->pseudo ?><br>
                Ressources pillées : <?= $loot_amount ?>
            <?php elseif ($army_att->get_total_units() <= 0): ?>
                Vainqueur : <?= $defender->pseudo ?>
            <?php else: ?>
                Aucun vainqueur
            <?php endif ?>
        </td>
    </tr>
    </tfoot>
</table>
