<table>
    <thead>
    <tr>
        <th>
            Attaquant : <?= $att['pseudo'] ?>
            <small><?= $att['start']['quantity'] ?> unité(s)</small>
        </th>
        <th>
            Défenseur :<?= $def['pseudo'] ?>
            <small><?= $def['start']['quantity'] ?> unité(s)</small>
        </th>
    </tr>
    <tr>
        <td>
            <ul>
                <?php foreach ($att['start']['troops'] as $unit): ?>
                    <?php if ($unit['quantity'] > 0): ?>
                        <li><?= $unit['quantity'] ?> <?= $unit['name'] ?></li>
                    <?php endif ?>
                <?php endforeach ?>
            </ul>
        </td>
        <td>
            <ul>
                <?php if ($def['start']['quantity'] > 0): ?>
                    <?php foreach ($def['start']['troops'] as $unit): ?>
                        <?php if ($unit['quantity'] > 0): ?>
                            <li><?= $unit['quantity'] ?> <?= $unit['name'] ?></li>
                        <?php endif ?>
                    <?php endforeach ?>
                <?php else: ?>
                    <li>Il n'y avait personne pour défendre cet empire</li>
                <?php endif ?>
            </ul>
        </td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($turns as $count => $turn): ?>
        <tr>
            <th colspan="2" class="text-center">Tour <?= $count ?></th>
        </tr>
        <tr>
            <td><?= $turn['att'] ?></td>
            <td><?= $turn['def'] ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan='2'>
            <?php if ($def['end']['quantity'] <= 0): ?>
                Vainqueur : <?= $att['pseudo'] ?><br>
                Ressources pillées : <?= $loot_amount ?>
            <?php elseif ($att['end']['quantity'] <= 0): ?>
                Vainqueur : <?= $def['pseudo'] ?>
            <?php else: ?>
                Aucun vainqueur
            <?php endif ?>
        </td>
    </tr>
    </tfoot>
</table>
