<footer class="container-fluid" id="footer">
    <div id="castel-bg"></div>
    <div class="container">
        <div class="col-6 center">
            <p>pied de page (des fois que vous ne l'auriez pas remarqué)</p>
        </div>
    </div>
</footer>

<!--  div for modal box -->
<div id="dialog-confirm"></div>

<!-- Ajax Loader -->
<img class="loading" src="<?= _TPL_ ?>img/loading.gif">
</body>
</html>