<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wardieval, jeu gratuit de stratègie médiévale</title>
    <meta name="author" content="ad-creatif">
    <meta name="langage" content="Fr-fr">

    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <link href='https://fonts.googleapis.com/css?family=Almendra:400,700|UnifrakturMaguntia|Astloch:700'
          rel='stylesheet' type='text/css'>
    <link href="<?= _TPL_ ?>css/responsive.css" rel="stylesheet">
    <link href="<?= _TPL_ ?>css/style.css" rel="stylesheet">
    <link href="<?= _TPL_ ?>css/jquery.prompt.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="<?= _TPL_ ?>js/jquery.countdown.min.js"></script>
    <script src="<?= _TPL_ ?>js/jquery.prompt.js"></script>
    <?php if ($userSession->isLogged()) { ?>
        <script>
            // variables globales accessibles en javascript
            _root_ = "<?= _TPL_ ?>";
            modifiers = <?= json_encode(CardsModel::getModifiers($user->id)) ?>;
            ressources = <?= $user->ressources ?>;

            $(function(){
                // mise à jour des ressources
                window.setInterval(function(){
                    ressources = ressources + parseInt(modifiers['income']);
                    $('#js-ressources').text(ressources.toLocaleString());
                }, 1000);
            });
        </script>
    <?php } ?>
    <script src="<?= _TPL_ ?>js/global.js"></script>
</head>

<body>
<header class="container-fluid">
    <div class="container">
        <div class="col-4 sm-full">
            <a href="<?= _HOME_ ?>" title="Wardieval, jeu gratuit de stratègie médiévale">
                <img class="responsive" src="<?= _TPL_ ?>img/logo.png">
            </a>
        </div>
        <nav class="col-6 sm-full main-menu ">
            <ul class="center">
                <?php if ($userSession->isLogged()) : ?>
                    <li><a class="btn-wood" href="<?= _HOME_ ?>empire">Empire</a></li>
                    <li><a class="btn-wood" href="<?= _HOME_ ?>cards">Boosters</a></li>
                    <li><a class="btn-wood" href="<?= _HOME_ ?>war">Guerre</a></li>
                <?php else : ?>
                    <li><a class="btn-wood" href="<?= _HOME_ ?>">Présentation</a></li>
                    <li><a class="btn-wood" href="<?= _HOME_ ?>register">Inscription</a></li>
                <?php endif ?>
            </ul>
        </nav>
        <div class="col-2 user-infos sm-inline silent">
            <?php if ($userSession->isLogged()) : ?>
                <ul>
                    <li><?= clean_html($user->pseudo) ?> <a href="<?= _HOME_ ?>logout">déconnexion</a>
                    </li>
                    <li>Score : <span><?= $user->score ?></span></li>
                    <li><i class="icon dollar"></i><span id="js-ressources"><?= $user->ressources ?></span>
                    </li>
                </ul>
            <?php else : ?>
                <form id="login" action="<?= _HOME_ ?>login" method="post">
                    <input type="text" name="pseudo" placeholder="pseudo">
                    <input type="password" name="pass" placeholder="mot de passe">
                    <input type="submit" name="submit" value="login">
                </form>
            <?php endif ?>
        </div>
    </div>
</header>
<?php if (!empty($errors) OR $userSession->haveFlashBag()) : ?>
    <section class="container">
        <ul class="col-12">
            <?php foreach ($errors as $error) : ?>
                <li><?= $error ?></li>
            <?php endforeach ?>
            <?php if ($userSession->haveFlashBag()): ?>
                <?php foreach ($userSession->fetchFlashBag() as $flashBag) : ?>
                    <li class="alert <?= !$flashBag['status'] ? 'alert-error' : 'alert-notif'; ?>"><?= $flashBag['message'] ?></li>
                <?php endforeach ?>
            <?php endif ?>
        </ul>
    </section>
<?php endif ?>

