
<h2 class="col-12">Mon empire</h2>
<div class="row">
    <div class="col-6 sm-full">
        <fieldset>
            <legend class="btn-wood-small">Construction d'unités</legend>
            <?php if (!empty($troops)): ?>
                <?php foreach ($troops as $unit_id => $troop) : ?>
                    <figure class="unit row" id="unit_<?= $unit_id ?>">
                        <div class="col-4">
                            <div class="unit-frame"
                                 style="background-image: url(<?= _TPL_ . 'img/units/' . $troop['image_name'] ?>)">
                                <img src="<?= _TPL_ ?>img/img-frame.png">
                            </div>
                        </div><!--
                        -->
                        <figcaption class="col-8">
                            <h4>
                                <?= $troop['name'] ?>
                                <small class="alert alert-info">possédé : <span class="js-quantity">
                                <?= $troop['quantity'] ?></span></small>
                            </h4>
                            <p><?= $troop['description'] ?></p>
                            <ul class="row">
                                <li><i class="icon dollar"></i><?= round($troop['price']) ?></li>
                                <li><i class="icon clock"></i><?= round($troop['building_time']) ?></li>
                                <li><i class="icon damages"></i><?= round($troop['damage']) ?></li>
                                <li><i class="icon life"></i><?= round($troop['life']) ?></li>
                            </ul>
                            <form method="post" class="unit-factory flex-left">
                                <label><input type="number" data-unit-id="<?= $unit_id ?>" name="quantity"
                                              placeholder="0" min="0"></label>
                                <button type="submit" name="submit" value="envoyer">Recruter</button>
                                <input type="hidden" name="unit_id" value="<?= $unit_id ?>">
                            </form>
                            <div class="js-info alert alert-info hide"></div>
                        </figcaption>
                    </figure>
                <?php endforeach ?>
            <?php else : ?>
                <h4>Désolé ! </h4>
                <p>un petit problème technique s'est produit. on est sur le coup ! </p>
            <?php endif ?>
        </fieldset>
    </div><!--
    -->
    <div class="col-6 sm-full">
        <fieldset>
            <!-- **************************** -->
            <!-- ****** FILE D'ATTENTE ****** -->
            <!-- **************************** -->
            <legend class="btn-wood-small">File d'attente</legend>
            <ul id="js-queue" class="building-queue">
                <li class="alert alert-info silent">Votre fille d'attente est vide pour le moment</li>
            </ul>
        </fieldset>


        <fieldset>
            <!-- **************************** -->
            <!-- ********* ATTAQUES ********* -->
            <!-- **************************** -->
            <legend class="btn-wood-small">Attaques en cours</legend>
            <ul id="js-outcoming-fleet">
                <?php if (!empty($troopsSent)) : ?>
                    <?php foreach ($troopsSent as $troop) : ?>
                        <li>
                            En route vers <b><?= clean_html($troop['pseudo']) ?></b>, arrivée prévue dans <span
                                    data-countdown="<?= $troop['arrival_time'] ?>"></span>
                            <a class="js-del ui-icon ui-icon-trash" href="#" data-fleet-id="<?= $troop['id'] ?>"></a>
                        </li>
                    <?php endforeach ?>
                <?php else : ?>
                    <li class="alert alert-info silent">Aucune attaque en cours ! Rendez-vous à la page <a
                                href="<?= _ROOT_ ?>war">guerre</a></li>
                <?php endif ?>
            </ul>
        </fieldset>


        <fieldset>
            <!-- **************************** -->
            <!-- ********* APPROCHE ********* -->
            <!-- **************************** -->
            <legend class="btn-wood-small">Armées en approche</legend>
            <ul id="js-incoming-fleet">
                <?php if (!empty($incomingAttacks)) : ?>
                    <?php foreach ($incomingAttacks as $troop): ?>
                        <li>
                            Attaque de <b><?= clean_html($troop['pseudo']) ?></b>, arrivée prévue dans
                            <span data-countdown="<?= $troop['arrival_time'] ?>"></span>
                        </li>
                    <?php endforeach ?>
                <?php else : ?>
                    <li class="alert alert-info silent">Nos guetteurs ne signalent rien à l'horizon</li>
                <?php endif ?>
            </ul>
        </fieldset>
    </div>
</div>

<script src="<?= _TPL_ ?>js/classes/QueueItem.class.js"></script>
<script src="<?= _TPL_ ?>js/classes/Empire.class.js"></script>
<script src="<?= _TPL_ ?>js/empire.js"></script>
<script>
    $(function () {
        new Empire();
    });
</script>
