<table>
    <thead>
    <tr>
        <th style=\"width:50%\">Attaquant : $attacker->pseudo<br>flotte : $army_att->total_units unité(s)</th>
        <th style=\"width:50%\">Défenseur : $defender->pseudo<br>flotte : $army_def->total_units unité(s)</th>
    </tr>
    <tr>
        <td>
            <ul>$mess_att</ul>
        </td>
        <td>
            <ul>$mess_def</ul>
        </td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($turns as $count => $turn): ?>
        <tr>
            <th colspan="2">Tour <?= $count ?></th>
        </tr>
        <tr>
            <td><?= $att_res ?></td>
            <td><?= $def_res ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan='2'>$result</td>
    </tr>
    </tfoot>
</table>