<div class="col-8 sm-full">
    <h2>Accueil</h2>

    <h3>What's new ?</h3>

    <ul id="functions">
        <li>Maj 11/06
            <ul>
                <li>Gestionaire d'erreurs</li>
                <li>Amélioration du design</li>
                <li></li>
            </ul>
        </li>
        <li>Maj 10/06
            <ul>
                <li>Infos bulles entre les pages</li>
                <li>Mail à l'inscription</li>
                <li>Refonte complète du moteur de combat</li>
                <li>Refonte complète des transactions ajax</li>
                <li>Equilibrage des scores</li>
                <li>Responsive</li>
            </ul>
        </li>
    </ul>
    <!--
        <ul id="functions">
            <li>Utilisateurs
                <ul>
                    <li>Création compte</li>
                    <li>Login</li>
                    <li>Sessions</li>
                </ul>
            </li>

            <li>Empire
                <ul>
                    <li>Création unités</li>
                    <li>gestion avancée files d'attente de construction</li>
                    <li>gestion des attaques en cours</li>
                    <li>affichage des flottes en approche</li>
                    <li>messages</li>
                </ul>
            </li>
            <li>Combats
                <ul>
                    <li>choix des cibles à portées</li>
                    <li>choix de la flotte à envoyer</li>
                    <li>résolution des combats</li>
                    <li>rapports de combats</li>
                    <li>pillages de ressources si victoire</li>
                </ul>
            </li>
            <li>Cartes
                <ul>
                    <li>intègration des modifiers</li>
                </ul>
            </li>

            <li>Stats
                <ul>
                    <li>Affichage du top 5</li>
                </ul>
            </li>
        </ul>
        -->
</div>
<div class="col-4 sm-full">
    <h3>Top 10 joueurs</h3>
    <ol>
        <?php

        foreach ($top_ten as $user)
            echo '<li>' . ucfirst(clean_html($user['pseudo'])) . ' - ' . $user['score'] . '</li>';
        ?>

    </ol>
</div>
