<form id="login" action="<?= _HOME_ ?>login" class="form" method="post">
    <fieldset class="col-8 center">
        <legend class="btn-wood">Informations d'inscription</legend>
        <li>
            <label for="pseudo">Pseudo</label>
            <input id="pseudo" type="text" name="pseudo" placeholder="pseudo">
        </li>
        <li>
            <label for="pass">mot de passe</label>
            <input id="pass" type="password" name="pass" placeholder="mot de passe">
        </li>
        <li>
            <input type="submit" name="submit" value="login">
        </li>
    </fieldset>
</form>
