<form id="login" action="<?= _HOME_ ?>login" class="form" method="post">
    <fieldset class="col-8 center">
        <legend class="btn-wood">Informations d'inscription</legend>
        <li>
            <label>
                <input type="text" name="pseudo" placeholder="pseudo"></label>
        </li>
        <li>
            <label>
                <input type="password" name="pass" placeholder="mot de passe"></label>
        </li>
        <li>
            <input type="submit" name="submit" value="login">
        </li>
    </fieldset>
</form>
