<h2>Combats</h2>
<?php if (isset($fleet_choice)): ?>
    <?php if ($troops): ?>
        <div id="unit-selection" class="row">
            <form method="post" class="col-8 offset-2 sm-full">
                <table>
                    <thead>
                    <tr>
                        <th class="text-left" span="2">
                            <?= clean_html($user->pseudo) . ' VS ' . clean_html($target->pseudo) ?>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($troops as $troop): ?>
                        <?php if ($troop['quantity'] > 0): ?>
                            <tr>
                                <td><?= $troop['name'] ?>
                                </td>
                                <td class="unit-quantity">
                                    <label>
                                        <input id="unitID_<?= $troop['id'] ?>" type="number"
                                               class="js-quantity input-number"
                                               name="unitID_<?= $troop['id'] ?>" placeholder="0" min="0"
                                               max="<?= $troop['quantity'] ?>">/ <?= $troop['quantity'] ?>
                                    </label>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="3">
                                    <div class="slider" data-unit-id="<?= $troop['id'] ?>"
                                         data-max="<?= $troop['quantity'] ?>"></div>
                                </td>
                            </tr>
                        <?php endif ?>
                    <?php endforeach ?>
                    </tbody>
                    <tr class="text-right">
                        <td colspan="2">
                            <input type="hidden" name="target_id" value="<?= $target->id ?>">
                            <button type="submit" name="start_war">start_war</button>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        <script>
            $(function () {
                $('.slider').slider({
                    animate: 'slow',
                    min: 0,
                    max: $(this).data('max'),
                    step: 1,
                    slide: function (evt, target) {
                        let max = $(this).data('max');
                        let unitId = $(this).data('unitId');
                        console.log(unitId);
                        console.log(target.value);
                        $('#unitID_' + unitId).val(Math.floor(max * target.value / 100));
                    }
                });
                $('.js-quantity').blur(function (e) {
                    let slider = $(this).closest('tbody').find('.slider');
                    let quantity = $(this).val() / slider.data('max') * 100;
                    slider.slider({value: quantity})
                })
            });
        </script>
    <?php else : ?>
        <p>Vous n'avez pas d'unités à envoyer</p>
    <?php endif ?>
<?php endif ?>

<?php if (isset($target_selection)) : ?>
    <?php if ($targets): ?>
        <ul class="players-list col-4 center">
            <?php foreach ($targets as $target): ?>
                <?php if ($user->id != $target['id']): ?>
                    <li>
                        <a href="<?= _HOME_ . 'war/attack/' . $target['id'] ?>">
                            <strong><?= clean_html(($target['pseudo'])) ?></strong> - <?= $target['score'] ?>
                        </a>
                    </li>
                <?php endif ?>
            <?php endforeach ?>
        </ul>
    <?php else: ?>
        <p>Aucun Joueur n'est à votre portée</p>
    <?php endif ?>
<?php endif ?>
